####################
# zsh
####################
export PATH=/opt/homebrew/bin:$PATH

export ZSH=~/.oh-my-zsh

ZSH_THEME="simple"

# disable auto-setting terminal title
DISABLE_AUTO_TITLE="true"

# init oh-my-zsh
source $ZSH/oh-my-zsh.sh

####################
# functions
####################
# discard all changes including added new files
gd() {
  git add .
  git commit --no-verify -m "dump" 1>/dev/null 2>&1
  git reset --hard HEAD^ 1>/dev/null 2>&1
}

# discard -> update -> prune
gu() {
  gd && git pull && git remote prune origin
}

# get git branch name by using fzf
fgb() {
  git for-each-ref --format="%(refname:lstrip=2)" "refs/heads" | fzf -m
}

# checkout branch by using fzf
fgc() {
  git checkout $(fgb)
}

# delete branch(es) by using fzf
fgbd() {
  git branch -D $(fgb)
}

# open github repo
vgr() {
  repo=$(git remote -v | head -1 | grep -E ":.*\." -o)
  repo=${repo#:}
  repo=${repo%.}
  open https://github.com/${repo}
}

# compress img
zipimg() {
  cur_name="$1"
  bkp_name="old-${cur_name}"
  echo "img: ${cur_name}"
  echo "compressing..."
  mv "${cur_name}" "${bkp_name}"
  ffmpeg -nostdin -hide_banner -loglevel error -i "${bkp_name}" "${cur_name}"
  echo "done"
  echo
  echo "old img: ${bkp_name}"
  echo "compressed img: ${cur_name}"
  echo
}

fzipimg() {
  fzf -m | while read filename; do
    zipimg "${filename}"
  done
}


####################
# export
####################
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# work dir
export WORKDIR=~/z

# fzf
export FZF_DEFAULT_COMMAND='fd --type f'

# pip
export PIP_CONFIG_FILE=~/.pip.conf

# pipenv, creates virtualenv inside project directory
export PIPENV_VENV_IN_PROJECT=1

# dart
export PATH="$PATH:$HOME/.pub-cache/bin"

# Antigravity
export PATH="$HOME/.antigravity/antigravity/bin:$PATH"


####################
# alias
####################
# Edit files
alias vishrc="vi ~/.zshrc && source ~/.zshrc"
alias vivimrc="vi ~/.vimrc"
alias vitmuxconf="vi ~/.tmux.conf"

# Go to directories
alias z="cd ~/z"
alias mk="cd ${WORKDIR}/monkey"
alias pj="cd ${WORKDIR}/projects"

# macos
alias showfiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hidefiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'

# pnpm
alias p=pnpm
